version: "3"

services:
  db:
    image: postgres
    platform: linux/amd64
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  stack-match-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - db
